### Numpy tutorial

In [4]:
!pip install numpy

     --------------------------------------- 14.7/14.7 MB 16.4 MB/s eta 0:00:00


In [5]:
import numpy as np

np.__version__

'1.23.1'

In [6]:
a = []

type(a)

list

[numpy 관련 사이트]

https://velog.io/@mingki/Numpy-%EB%84%98%ED%8C%8C%EC%9D%B4

___

## ndarray 클래스

In [8]:
xarr = np.array([23, 45, 56, 76])

print(xarr)

xarr

[23 45 56 76]


array([23, 45, 56, 76])

In [9]:
type(xarr)

numpy.ndarray

In [10]:
xarr.shape

(4,)

In [14]:
xarr.dtype

# int32, int64, float32, float64

dtype('int32')

In [18]:
xarr.size

# 요소 개수

4

In [23]:
xarr.itemsize

# byte

4

In [25]:
xarr.itemsize * xarr.size

# 메모리 사이즈

16

In [31]:
yarr = np.array([[[1,2],[3, 4]],[[5, 6], [7, 8]],[[9,10],[11,12]]]) # 3차원
# 2차원  np.array([[10, 11],[12, 13],[15, 16]])
yarr.shape

(3, 2, 2)

In [32]:
yarr

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [33]:
yarr.dtype

dtype('int32')

In [34]:
type(yarr)

numpy.ndarray

In [35]:
yarr.astype('float32')

array([[[ 1.,  2.],
        [ 3.,  4.]],

       [[ 5.,  6.],
        [ 7.,  8.]],

       [[ 9., 10.],
        [11., 12.]]], dtype=float32)

In [36]:
yarr.dtype

dtype('int32')

In [37]:
yarr = yarr.astype('float32')

In [38]:
yarr.dtype

dtype('float32')

In [41]:
xarr = np.array([23., 45., 56., 76.], dtype='int32') # float64 -> int32
xarr.dtype

dtype('int32')

In [75]:
yarr = np.array([[[1,2],[3, 4]],
                 [[5, 6], [7, 8]],
                 [[9,10],[11,12]]]) # 3차원
yarr.shape

(3, 2, 2)

In [76]:
yarr = yarr.reshape(1, 3, 2, 2)
yarr.shape

(1, 3, 2, 2)

In [77]:
yarr

array([[[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]],

        [[ 9, 10],
         [11, 12]]]])

In [78]:
yarr = yarr.reshape(-1, 3, 2, 2)
# 첫번째 인자 -1 -> reshape 한테 차원을 추가시키고 값은 알아서 넣어줘?
yarr.shape

(1, 3, 2, 2)

In [79]:
yarr.reshape(-1, 2, 2).shape
# -1 -> 3 으로 reshpae 가 넣어줌 (배치 수는 맡김)

(3, 2, 2)

In [80]:
yarr.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [81]:
yarr.reshape(-1) # flatten() 모르면 이와 같이 작성하여 확인 가능

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [82]:
yarr.shape

(1, 3, 2, 2)

In [85]:
yarr[np.newaxis, :].shape # reshape 다르게 작성

(1, 1, 3, 2, 2)

값 하나하나 읽어오는데 **indexing**

어떤 조건을 주고 해당 좋건에 맞는 값만 가져오는게 **slicing**

___

In [88]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [94]:
xarr = np.arange(10).reshape(5, 2)
xarr

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [95]:
xarr = np.arange(0, 10, 2)
xarr

array([0, 2, 4, 6, 8])

In [97]:
np.linspace(0, 10, 8) # 0~10 의 숫자 8개

array([ 0.        ,  1.42857143,  2.85714286,  4.28571429,  5.71428571,
        7.14285714,  8.57142857, 10.        ])

In [98]:
np.full((2, 3), 0)

array([[0, 0, 0],
       [0, 0, 0]])

In [99]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [100]:
yarr.shape

(1, 3, 2, 2)

In [106]:
yarr = yarr.reshape(3,2,2)
yarr

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [104]:
np.zeros_like(yarr) # yarr과 같은 배열구조를 0으로 채워 만듦

array([[[0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0]]])

## random

In [109]:
np.random.uniform(0, 10, 10) # 같은 확률로 숫자 하나를 뽑는다

array([6.61387693, 1.06343344, 2.99173668, 1.07768543, 0.65039349,
       8.80982263, 8.48444742, 7.33680513, 9.81231993, 8.75238301])

In [114]:
np.random.normal(5, 1, 10)  # 정규 분포 (평균, 표준편차, 숫자개수)

array([5.28795934, 5.76258864, 5.65090591, 2.99568414, 5.50098131,
       2.23776215, 4.10574087, 5.52848507, 4.73512478, 4.02474445])

In [116]:
np.random.randn(2,3)  # 표준 정규 분포 (평균=0,표준편차=1) randn(차원)

array([[-0.08023808, -0.65413371, -0.56782216],
       [ 0.31570141,  0.53900135, -0.74931154]])

## 함수

In [118]:
xarr = np.arange(0, 12).reshape(3, 4)
xarr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [120]:
xarr.sum()  # 총합

66

In [121]:
xarr.sum(axis=0)

array([12, 15, 18, 21])

In [122]:
xarr.sum(axis=1)

array([ 6, 22, 38])

In [123]:
np.sum(xarr, axis=1)

array([ 6, 22, 38])

In [124]:
xarr.mean(axis=0)  # 평균

array([4., 5., 6., 7.])

In [126]:
np.mean(xarr, axis = 0)
# 변수.함수(축) 는 대부분 np.함수(변수, 축) 로도 사용 가능

array([4., 5., 6., 7.])

In [127]:
xarr.min(axis=0)

array([0, 1, 2, 3])

In [128]:
xarr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [131]:
xarr + 3  # 내부적으로 boradcasting 일어나서 가능 (안되는 구조도 있음)

array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10],
       [11, 12, 13, 14]])

In [133]:
xarr + [3]

array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10],
       [11, 12, 13, 14]])

In [134]:
xarr + np.array([3,2])

ValueError: operands could not be broadcast together with shapes (3,4) (2,) 

In [135]:
xarr * 2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [137]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[1, 2], [3, 4]])

In [139]:
x * y

array([[ 1,  4],
       [ 9, 16]])

In [140]:
x @ y  # 행렬의 곱

array([[ 7, 10],
       [15, 22]])

In [149]:
x = np.array([1, 2, 3])
y = np.array([1, 2, 3])

In [150]:
np.dot(x, y)  # 같은 자리 곱해서 다 더하기

14

In [151]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[1, 2], [3, 4]])

np.dot(x, y)  # 2차원 넘어가면 행렬곱

array([[ 7, 10],
       [15, 22]])

In [153]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[1, 2], [3, 4]])

np.matmul(x, y)  # 행렬곱 해주는 함수

array([[ 7, 10],
       [15, 22]])

In [155]:
x = np.array([1, 2, 3])
x > 2    
# 결과 리스트를 받으려는게 아니라 이 조건에 맞는 값이 어떤 것인지 보고 가져오기 위함

array([False, False,  True])

In [161]:
# x[[False, True, True, False]]

# array([4,3])

x[x > 2]  # 기준에 맞는 데이터를 없애거나 가져오기 위해 (이상치 처리)

array([3])

In [162]:
x = [1, 2, 3]
y = [4, 5, 6]

In [168]:
np.concatenate((x, y), axis=0)  # 합치기

array([1, 2, 3, 4, 5, 6])

In [172]:
np.vstack((x, y)) # vertical 로 합치기

array([[1, 2, 3],
       [4, 5, 6]])

In [174]:
np.hstack((x,y))  # horizonal 로 합치기

array([1, 2, 3, 4, 5, 6])

In [183]:
x = np.array([1, 2, 3, 4]).reshape(2,2)
y = np.array([4, 5, 6, 7]).reshape(2,2)

In [184]:
np.concatenate((x,y), axis=0)

array([[1, 2],
       [3, 4],
       [4, 5],
       [6, 7]])

In [185]:
np.concatenate((x,y), axis=1)

array([[1, 2, 4, 5],
       [3, 4, 6, 7]])

In [187]:
x = [[1,2],[3,4]]
x

[[1, 2], [3, 4]]

In [188]:
print(x[1][0])

3


In [190]:
x = np.array([[1,2], [3,4]])
x[1,0]  # ndarray | python -> x[1][0]

3

In [266]:
x = np.array([1, 2, 3, 4, 5])
x

array([1, 2, 3, 4, 5])

In [267]:
np.where(x > 3)

(array([3, 4], dtype=int64),)

In [268]:
np.where(x > 3, 1, 0)  # 3보다 크면 1, 작으면 0

array([0, 0, 0, 1, 1])

In [269]:
x = np.array([1, 2, 3, 4, 5, 6])
x = np.where(x > 3, 1, 0)
x.sum()  # '1' (3보다 큰 값)의 개수를 알 수 있음

3

In [270]:
x = np.random.randn(4, 3)
x

array([[-2.08290392, -0.37219084, -0.24048417],
       [-1.11228163, -1.47811447, -2.12327673],
       [ 1.0614371 ,  1.28352761,  0.34346872],
       [ 0.43077683,  0.97481727,  2.08968604]])

In [271]:
np.argmax(x, axis=1)  # 열마다 최댓값의 인덱스

array([2, 0, 1, 2], dtype=int64)

In [272]:
np.argmin(x, axis =1)  # 열마다 최솟값의 인덱스

array([0, 2, 2, 0], dtype=int64)

In [273]:
xarr = np.array([1, 2, 3, 4, 5, 6, 7])  # 뒤에 .copy 붙이면 원본 데이터 안바뀜
xarr

array([1, 2, 3, 4, 5, 6, 7])

In [274]:
xarr[0:5]
# xarr[:5] xarr[:] 전부다 xarr[:-1] 마지막꺼 빼고 나머지 xarr[-1] 마지막꺼만

array([1, 2, 3, 4, 5])

In [275]:
# X = xarr[:-1] target 값 제외한 데이터
# Y = xarr[-1]  target 값

In [276]:
y = xarr[3:5]
y

array([4, 5])

In [277]:
y[0] = -1
y

array([-1,  5])

In [278]:
xarr

array([ 1,  2,  3, -1,  5,  6,  7])

In [293]:
iris = np.genfromtxt('./datasets/iris.csv', delimiter=',', skip_header=1)
iris[:5]

array([[5.1, 3.5, 1.4, 0.2, nan],
       [4.9, 3. , 1.4, 0.2, nan],
       [4.7, 3.2, 1.3, 0.2, nan],
       [4.6, 3.1, 1.5, 0.2, nan],
       [5. , 3.6, 1.4, 0.2, nan]])

In [294]:
iris.shape

(150, 5)

In [295]:
iris.dtype

dtype('float64')

In [296]:
xarr = iris[:,:-1] # 나는 iris[:,0:4] 라고 했음


In [297]:
xarr[:,0].mean()

5.843333333333334

In [298]:
m = 5.8
x = xarr[xarr[:,0] > 5.8 , :]
y = xarr[xarr[:,0] <= 5.8 , :]

In [299]:
x[:,0].min()

5.9

In [300]:
y[:,0].max()

5.8

In [301]:
x.shape

(70, 4)

In [302]:
y.shape

(80, 4)

In [303]:
np.savez('my_iris.npz', my_x=x, my_y=y)

In [304]:
!dir

 C 드라이브의 볼륨에는 이름이 없습니다.
 볼륨 일련 번호: C63E-484E

 C:\Users\042 디렉터리

2022-07-14  오후 02:53    <DIR>          .
2022-05-18  오후 01:29    <DIR>          ..
2022-07-08  오후 05:24    <DIR>          .android
2022-07-04  오후 02:15    <DIR>          .azure
2022-07-14  오후 02:58    <DIR>          .conda
2022-07-14  오전 10:12                25 .condarc
2022-07-14  오전 10:11    <DIR>          .continuum
2022-07-06  오전 10:11                16 .emulator_console_auth_token
2022-07-11  오후 05:05                51 .gitconfig
2022-07-06  오전 09:53    <DIR>          .gradle
2022-07-11  오전 09:59    <DIR>          .idlerc
2022-07-14  오후 12:31    <DIR>          .ipynb_checkpoints
2022-07-01  오전 09:44    <DIR>          .ipython
2022-07-14  오전 10:12    <DIR>          .jupyter
2022-07-11  오후 05:05                20 .lesshst
2022-07-06  오전 09:55    <DIR>          .m2
2022-07-01  오전 10:22    <DIR>          .matplotlib
2022-07-08  오후 05:41    <DIR>          .nbi
2022-06-30  오전 08:59    <DIR>          .VirtualBox
2022-07-11

In [305]:
my_iris = np.load('my_iris.npz')
type(my_iris)

numpy.lib.npyio.NpzFile

In [306]:
xarr = my_iris['my_x']
type(xarr)

numpy.ndarray

In [307]:
xarr

array([[7. , 3.2, 4.7, 1.4],
       [6.4, 3.2, 4.5, 1.5],
       [6.9, 3.1, 4.9, 1.5],
       [6.5, 2.8, 4.6, 1.5],
       [6.3, 3.3, 4.7, 1.6],
       [6.6, 2.9, 4.6, 1.3],
       [5.9, 3. , 4.2, 1.5],
       [6. , 2.2, 4. , 1. ],
       [6.1, 2.9, 4.7, 1.4],
       [6.7, 3.1, 4.4, 1.4],
       [6.2, 2.2, 4.5, 1.5],
       [5.9, 3.2, 4.8, 1.8],
       [6.1, 2.8, 4. , 1.3],
       [6.3, 2.5, 4.9, 1.5],
       [6.1, 2.8, 4.7, 1.2],
       [6.4, 2.9, 4.3, 1.3],
       [6.6, 3. , 4.4, 1.4],
       [6.8, 2.8, 4.8, 1.4],
       [6.7, 3. , 5. , 1.7],
       [6. , 2.9, 4.5, 1.5],
       [6. , 2.7, 5.1, 1.6],
       [6. , 3.4, 4.5, 1.6],
       [6.7, 3.1, 4.7, 1.5],
       [6.3, 2.3, 4.4, 1.3],
       [6.1, 3. , 4.6, 1.4],
       [6.2, 2.9, 4.3, 1.3],
       [6.3, 3.3, 6. , 2.5],
       [7.1, 3. , 5.9, 2.1],
       [6.3, 2.9, 5.6, 1.8],
       [6.5, 3. , 5.8, 2.2],
       [7.6, 3. , 6.6, 2.1],
       [7.3, 2.9, 6.3, 1.8],
       [6.7, 2.5, 5.8, 1.8],
       [7.2, 3.6, 6.1, 2.5],
       [6.5, 3